### ISSUE TITLE
Relation TypeError w. Sympy v.1.0's Heaviside implementation

### ISSUE THREAD

**Issue by espenhgn** [AllenInstitute/dipde#6] opened 2016-06-29 08:54 UTC
In the latest version of sympy, Heaviside(0.0) is not defined. The old definition would be Heaviside(0.0) = 1/2. Thus, the potjans example script fails with a TypeError:

    In [1]: run potjans_diesmann_cortical_column.py
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /Users/ehagen/Repositories/dipde/dipde/examples/potjans_diesmann_cortical_column.py in <module>()
        113 
        114 # Run simulation:
    --> 115 simulation.run(dt=dt, tf=tf, t0=t0)
        116 
        117 # Visualize:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/simulation.pyc in run(self, t0, dt, tf)
        102         # Initialize:
        103         start_time = time.time()
    --> 104         self.initialize(t0=t0)
        105         self.initialization_time = time.time() - start_time
        106 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/simulation.pyc in initialize(self, t0)
         73         # Initialize populations:
         74         for p in self.population_list:
    ---> 75             p.initialize()
         76 
         77         # Initialize connections:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/internalpopulation.pyc in initialize(self)
        120         self.initialize_edges()
        121         self.initialize_probability()  # TODO: different initialization options
    --> 122         self.initialize_total_input_dict()
        123         if self.record == True: self.initialize_firing_rate_recorder()
        124 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/internalpopulation.pyc in initialize_total_input_dict(self)
        191                 c.initialize_connection_distribution()
        192                 curr_input = self.total_input_dict.setdefault(c.connection_distribution, 0)
    --> 193             self.total_input_dict[c.connection_distribution] = curr_input + c.curr_delayed_firing_rate * c.nsyn
        194 
        195     def get_total_flux_matrix(self):
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/connection.pyc in curr_delayed_firing_rate(self)
        146             return self.delay_queue[0]
        147         except:
    --> 148             self.initialize_delay_queue()
        149             return self.delay_queue[0]
        150 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/connection.pyc in initialize_delay_queue(self)
        123             self.delay_queue = np.core.numeric.zeros(self.delay_ind+1)
        124             for i in range(len(self.delay_queue)):
    --> 125                 self.delay_queue[i] = self.source.firing_rate(self.simulation.t - self.simulation.dt*i)
        126                 self.delay_queue = self.delay_queue[::-1]
        127         else:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/externalpopulation.pyc in firing_rate(self, t)
         63         curr_firing_rate = self.closure(t)
         64 
    ---> 65         if curr_firing_rate < 0:
         66             raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover
         67         # try:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy/core/relational.pyc in __nonzero__(self)
        193 
        194     def __nonzero__(self):
    --> 195         raise TypeError("cannot determine truth value of Relational")
        196 
        197     __bool__ = __nonzero__
    
    TypeError: cannot determine truth value of Relational       

An ugly fix capturing the TypeError would be:

            def firing_rate(self, t):
            '''Firing rate of the population at time t (Hz).''' 
            
            curr_firing_rate = self.closure(t)
    
            # if curr_firing_rate < 0:
            #     raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover
            try:
                if curr_firing_rate < 0:
                    raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover
            except TypeError as te:
                curr_firing_rate /= Heaviside(0.0) * 2
                if curr_firing_rate < 0:
                    raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover
            
            return curr_firing_rate

**Comment by nicain** [comment] 2016-06-29 16:52
Hi Espen,

Thanks for reaching out, and bringing this to our attention.  You also have the distinction of being the first person to do so!

Can you please provide me with the scipy version number that reproduces the error, so that I can make a unit test and work on a fix?

Also, I have just recently (10 minutes ago!) made a google group for dipde: https://groups.google.com/forum/#!forum/dipde  If you are so inclined, feel free to join.  Ill begin using this for communications about the project; there will be more to come soon!

Best,
-n




On Jun 29, 2016, at 1:54 AM, Espen Hagen <notifications@github.com<mailto:notifications@github.com>> wrote:


In the latest version of sympy, Heaviside(0.0) is not defined. The old definition would be Heaviside(0.0) = 1/2. Thus, the potjans example script fails with a TypeError:

In [1]: run potjans_diesmann_cortical_column.py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/ehagen/Repositories/dipde/dipde/examples/potjans_diesmann_cortical_column.py in <module>()
    113
    114 # Run simulation:
--> 115 simulation.run(dt=dt, tf=tf, t0=t0)
    116
    117 # Visualize:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/simulation.pyc in run(self, t0, dt, tf)
    102         # Initialize:
    103         start_time = time.time()
--> 104         self.initialize(t0=t0)
    105         self.initialization_time = time.time() - start_time
    106

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/simulation.pyc in initialize(self, t0)
     73         # Initialize populations:
     74         for p in self.population_list:
---> 75             p.initialize()
     76
     77         # Initialize connections:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/internalpopulation.pyc in initialize(self)
    120         self.initialize_edges()
    121         self.initialize_probability()  # TODO: different initialization options
--> 122         self.initialize_total_input_dict()
    123         if self.record == True: self.initialize_firing_rate_recorder()
    124

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/internalpopulation.pyc in initialize_total_input_dict(self)
    191                 c.initialize_connection_distribution()
    192                 curr_input = self.total_input_dict.setdefault(c.connection_distribution, 0)
--> 193             self.total_input_dict[c.connection_distribution] = curr_input + c.curr_delayed_firing_rate * c.nsyn
    194
    195     def get_total_flux_matrix(self):

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/connection.pyc in curr_delayed_firing_rate(self)
    146             return self.delay_queue[0]
    147         except:
--> 148             self.initialize_delay_queue()
    149             return self.delay_queue[0]
    150

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/connection.pyc in initialize_delay_queue(self)
    123             self.delay_queue = np.core.numeric.zeros(self.delay_ind+1)
    124             for i in range(len(self.delay_queue)):
--> 125                 self.delay_queue[i] = self.source.firing_rate(self.simulation.t - self.simulation.dt*i)
    126                 self.delay_queue = self.delay_queue[::-1]
    127         else:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dipde-0.1.0-py2.7.egg/dipde/internals/externalpopulation.pyc in firing_rate(self, t)
     63         curr_firing_rate = self.closure(t)
     64
---> 65         if curr_firing_rate < 0:
     66             raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover
     67         # try:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy/core/relational.pyc in __nonzero__(self)
    193
    194     def __nonzero__(self):
--> 195         raise TypeError("cannot determine truth value of Relational")
    196
    197     __bool__ = __nonzero__

TypeError: cannot determine truth value of Relational


An ugly fix capturing the TypeError would be:

        def firing_rate(self, t):
        '''Firing rate of the population at time t (Hz).'''

        curr_firing_rate = self.closure(t)

        # if curr_firing_rate < 0:
        #     raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover
        try:
            if curr_firing_rate < 0:
                raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover
        except TypeError as te:
            curr_firing_rate /= Heaviside(0.0) * 2
            if curr_firing_rate < 0:
                raise RuntimeError("negative firing rate requested: %s, at t=%s" % (self.firing_rate_string, t)) # pragma: no cover

        return curr_firing_rate

**Comment by espenhgn** [comment] 2016-07-03 02:45
Hi, sorry about the late response. My scipy version is 0.17.1

**Comment by nicain** [comment] 2016-09-27 19:54
Duplicate of #7 ; closing and merging

**Closed** 2016-09-27 19:58 UTC
Labels: duplicate
